image: gcc
before_script:
    - apt-get update && apt-get install -y cmake
    - apt-get update && apt-get install -y g++
    - echo `g++ --version`

build:
    script: |
            for dirname in hw*; do
              echo $dirname;
              cd $dirname;
              if [ -f "Makefile" ]; then
                make;
              else
                mkdir build;
                pushd build;
                CXX=g++ cmake ..;
                make;
                popd;
              fi;
              cd ..;
            done;